### PR TITLE
Adds http endpoints to ingest and adds cli/api to remove tilesets.

### PR DESCRIPTION
**Pull request by mildewey**
Adds the following two http api endpoints for ingesting and removing tilesets. The api for ingesting at tileset follows the same conventions (and code path) as the primary ingestion CLI, but also allows for downloading from any standard url.

```
POST localhost:8888/api/v1/ingest_tileset_by_url/
{
    "fileurl": "http://sci.utah.edu/~cvachet/Documents/BIDAC/Project_ARUP/data_synthetic/sim_02/output_hitile/sim_02_sorted.ballele.hitile",
    "uid": "sim_02_sorted.ballele",
    "name": "sim_02_sorted.ballele",
    "filename": "sim_02_sorted.ballele.hitile",
    "datatype": "vector",
    "filetype": "hitile",
    "coordSystem": "",
    "coordSystem2": "",
    "project_name": ""
}

DELETE localhost:8888/api/v1/remove_tilesets_by_uid/
{
  "uids": ["sim_02_sorted.ballele"]
}
```

Also adds a corresponding CLI for removing tilesets:
```
remove_tileset <uuid>
```

### CODE REVIEW

**Comment by mildewey** [comment]
Update from original description: I removed the (now duplicated) remove_tileset and replaced it with the implementation of delete_tileset previously contributed.

**Comment by flekschas** [comment]
@mildewey Did you see #80? That PR added an endpoint for removing tilesets already. E.g., `DELETE http://localhost:8000/api/v1/tilesets/${uuid}/`. Maybe it already fulfills your use case?

Regarding the other endpoint for adding new tilesets, I would advocate for RESTful endpoints as implemented in #80 for example. `POST` and `/ingest_tileset_by_url` is redundant. How about `POST` `/tilesets/` and `PUT` `/tilesets/${uuid}`. Also, `POST` together with a `uuid` would lead to conflicts because `POST` is not idempotent but `PUT` is. More generally, in this scenario I would not use `POST` because it could lead to accidental duplication (e.g., `POST`ing 3 times the same data should create 3 different tilesets in the db). This can't happen with `PUT` and `/tilesets/${uuid}` on the other hand.

**Comment by mildewey** [comment]
@flekschas I did this work before 80 and didn't realize that it had what I needed until after I created the PR. I've since updated my code to take advantage of delete_tilesets rather than recreating it.

As for the other concerns, I did take time to investigate using the ModelViewSet and concluded it wasn't adequate for what I was trying to do (or at least there were numerous pitfalls I was wary of). `DELETE http://localhost:8000/api/v1/tilesets/${uuid}/` doesn't work because the UUID is not the primary key, which the ModelViewSet depends on. The primary key is an autoincremented value that is not currently transparent in the code base (correct me if I'm wrong). PUT does not work for similar reasons. More significantly, downloading URLs is not supported by the tilesets api and I wouldn't necessarily expect it to be and so I felt it appropriate to add another endpoint to handle that specific case.

I do, however, agree that getting to a better REST paradigm would be valuable. If you have some concrete suggestions on how we can update the tilesets api to handle these cases, I'm happy to do the legwork of updating this PR.

**Comment by pkerpedjiev-zymergen** [comment]
> DELETE http://localhost:8000/api/v1/tilesets/${uuid}/ doesn't work because the UUID is not the primary key

Are you sure about that? I think it should because we've set `lookup_field='uuid'` in TilesetsViewSet (https://github.com/higlass/higlass-server/blob/225a0ad8194c844e7949a45416609faabeed2fe2/tilesets/views.py#L697) so it should work using the URL that you've described.

As for ingesting datasets, you can use the `/api/v1/tilesets/` endpoint. Simply posting to that will create a dataset. Here's an example: http://docs-dev.higlass.io/data_preparation.html#importing-into-higlass

Unfortunately that documentation is not in the most obvious place. What we really need is a section on the REST API here: https://github.com/higlass/higlass/tree/develop/docs

**Comment by mildewey** [comment]
RE: deletion As an example, GET .../api/v1/tilesets returns:
```
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "uuid": "sim_02_sorted.ballele",
            "datafile": "http://127.0.0.1:8888/api/v1/tilesets/media/sim_02_sorted.ballele.hitile",
            "filetype": "hitile",
            "datatype": "vector",
            "private": false,
            "name": "sim_02_sorted.ballele",
            "coordSystem": "",
            "coordSystem2": "",
            "created": "2018-11-30T17:32:02.890653Z"
        }
    ]
}
```
DELETE .../api/v1/tilesets/sim_02_sorted.ballele/ returns:
```
<h1>Not Found</h1>
<p>The requested URL /api/v1/tilesets/sim_02_sorted.ballele/ was not found on this server.</p>
```

RE: the POST command, that would work great if it accepted http style urls. Is that the direction I should go with this PR? expanding the datafile to be able to accept urls and not just paths?

**Comment by mildewey** [comment]
Superseded by PR #89

**Pull request closed without merging**
